[workspace]
name = "slam_bench"
channels = [
    "robostack-jazzy",
    "nvidia",
    "conda-forge",
    "pytorch",
    "https://prefix.dev/robostack-jazzy",
    "https://prefix.dev/conda-forge",
]
platforms = ["linux-64"]

# ============================================
# Default for all environments
# ============================================
[dependencies]
# Build tools
cmake = "*"
ninja = "*"
make = "*"
pkg-config = "*"
compilers = "*"
pytest = "*"
ipykernel = "*"
[tasks]
build = "colcon build --symlink-install"
clean = "rm -rf build install log"
test = { cmd = "colcon test", description = "Run tests for the workspace" }

[activation.env]
# CycloneDDS
# RMW_IMPLEMENTATION = "rmw_cyclonedds_cpp"
# ROS_DOMAIN_ID = "6"

# ============================================
# Feature: ROS2
# ============================================
[feature.ros2.dependencies]
# ROS2 packages
ros-jazzy-desktop-full = "*"
ros-jazzy-rmw-cyclonedds-cpp = "*"
ros-jazzy-ros-gz = "*"
ros-jazzy-rviz2 = "*"
ros-jazzy-rqt-common-plugins = "*"
ros-jazzy-ros-base = "*"
ros-jazzy-ros2cli = "*"

# Build tools for Python packages
colcon-common-extensions = "*"
setuptools = "==68.1.2"

# Build tools for C++ packages
ros-jazzy-ament-cmake-auto = "*"

# Workspace dependencies
ros-jazzy-ament-cmake = "*"
ros-jazzy-ament-cmake-copyright = "*"
ros-jazzy-ament-cmake-cppcheck = "*"
ros-jazzy-ament-cmake-lint-cmake = "*"
ros-jazzy-ament-cmake-pep257 = "*"
ros-jazzy-ament-cmake-uncrustify = "*"
ros-jazzy-ament-cmake-xmllint = "*"
ros-jazzy-ament-copyright = "*"
ros-jazzy-ament-flake8 = "*"
ros-jazzy-ament-lint-auto = "*"
ros-jazzy-ament-pep257 = "*"
ros-jazzy-backward-ros = "*"
ros-jazzy-builtin-interfaces = "*"
ros-jazzy-compressed-depth-image-transport = "*"
ros-jazzy-compressed-image-transport = "*"
ros-jazzy-cv-bridge = "*"
ros-jazzy-diagnostic-msgs = "*"
ros-jazzy-diagnostic-updater = "*"
ros-jazzy-geographic-msgs = "*"
ros-jazzy-geometry-msgs = "*"
ros-jazzy-image-transport = "*"
ros-jazzy-image-transport-plugins = "*"
ros-jazzy-launch-ros = "*"
ros-jazzy-nav-msgs = "*"
ros-jazzy-nmea-msgs = "*"
ros-jazzy-pcl-conversions = "*"
ros-jazzy-pcl-msgs = "*"
ros-jazzy-pcl-ros = "*"
ros-jazzy-rclcpp = "*"
ros-jazzy-rclcpp-components = "*"
ros-jazzy-rclpy = "*"
ros-jazzy-rcutils = "*"
ros-jazzy-robot-localization = "*"
ros-jazzy-rosgraph-msgs = "*"
ros-jazzy-rosidl-default-generators = "*"
ros-jazzy-rosidl-default-runtime = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-shape-msgs = "*"
ros-jazzy-std-msgs = "*"
ros-jazzy-std-srvs = "*"
ros-jazzy-stereo-msgs = "*"
ros-jazzy-tf2 = "*"
ros-jazzy-tf2-geometry-msgs = "*"
ros-jazzy-tf2-ros = "*"
ros-jazzy-theora-image-transport = "*"
ros-jazzy-visualization-msgs = "*"
ros-jazzy-xacro = "*"
evo = ">=1.34.2,<2"

[feature.ros2.activation]
scripts = ["ros2_ws/install/setup.sh"]

# ============================================
# Feature: ZED SDK ROS 2 Bridge
# ============================================
[feature.zed.dependencies]
# Build tools for Python packages
colcon-common-extensions = "*"
setuptools = "==68.1.2"

# Build tools for C++ packages
ros-jazzy-ament-cmake-auto = "*"

# Dependencies required specifically for the zed-ros2-wrapper
ros-jazzy-ros-base = "*"
ros-jazzy-rclcpp = "*"
ros-jazzy-rclcpp-components = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-geometry-msgs = "*"
ros-jazzy-nav-msgs = "*"
ros-jazzy-tf2-ros = "*"
ros-jazzy-image-transport = "*"
ros-jazzy-diagnostic-updater = "*"
ros-jazzy-robot-state-publisher = "*"
ros-jazzy-xacro = "*"
ros-jazzy-nmea-msgs = "*"
ros-jazzy-geographic-msgs = "*"
ros-jazzy-stereo-msgs = "*"
ros-jazzy-diagnostic-msgs = "*"
ros-jazzy-visualization-msgs = "*"
ros-jazzy-robot-localization = "*"
ros-jazzy-image-transport-plugins = "*"
ros-jazzy-compressed-image-transport = "*"
ros-jazzy-compressed-depth-image-transport = "*"
ros-jazzy-theora-image-transport = "*"
ros-jazzy-tf2-geometry-msgs = "*"
ros-jazzy-rosgraph-msgs = "*"
ros-jazzy-backward-ros = "*"
ros-jazzy-std-srvs = "*"
ros-jazzy-std-msgs = "*"
ros-jazzy-builtin-interfaces = "*"
ros-jazzy-rcutils = "*"
ros-jazzy-launch-ros = "*"
lttng-ust = "*"

[feature.zed.activation.env]
# Bridge ZED SDK (System) to Pixi
CMAKE_PREFIX_PATH = "/usr/local/zed:$CMAKE_PREFIX_PATH"
LD_LIBRARY_PATH = "/usr/local/zed/lib:$LD_LIBRARY_PATH"

# ============================================
# Feature: CUDA 12.8
# ============================================
[feature.cuda.dependencies]
gcc_linux-64 = "11.*"
gxx_linux-64 = "11.*"
cuda = { version = "12.8.*", channel = "conda-forge" }
# cuda-nvcc = "12.8.*"
# cuda-cudart = "12.8.*"
# cuda-libraries = "12.8.*"
# cuda-nvrtc = "12.8.*"

# cuda-driver-dev = "12.8.*"
# cuda-cudart-dev = "12.8.*"

[feature.cuda.pypi-dependencies]
tensorrt-cu12 = ">10.11"
torch = { version = "*", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu128" }
torch-scatter = { url = "https://data.pyg.org/whl/torch-2.10.0%2Bcu128/torch_scatter-2.1.2%2Bpt210cu128-cp312-cp312-linux_x86_64.whl" }

[feature.cuda.activation.env]
CUDA_HOME = "${CONDA_PREFIX}"
# CPATH = "${CONDA_PREFIX}/targets/x86_64-linux/include:${CONDA_PREFIX}/include"
# LIBRARY_PATH = "${CONDA_PREFIX}/targets/x86_64-linux/lib:${CONDA_PREFIX}/lib"
# TORCH_NVCC_FLAGS = "-I${CONDA_PREFIX}/targets/x86_64-linux/include"
# ============================================
# Feature: Depth Anything 3
# ============================================
[feature.da3.dependencies]
numpy = "<2"
opencv = "*"
faiss-gpu = "*"
python = "3.11.*"
pandas = "*"
prettytable = "*"
numba = "*"
evo = "*"
pillow = "*"
requests = "*"
fastapi = "*"
uvicorn = "*"
typer = "*"
moviepy = "*"
pycolmap = "*"
huggingface_hub = "*"
einops = "*"
eigen = "*"
safetensors = "*"
trimesh = "*"
imageio = "*"
omegaconf = "*"
# libopenblas = { version = ">=0.3.31,<0.4", channel = "conda-forge" }
# libblas = { version = "*", build = "*openblas", channel = "conda-forge" }
# libcblas = { version = "*", build = "*openblas", channel = "conda-forge" }

[feature.da3.pypi-dependencies]
pypose = "*"
depth-anything-3 = { path = "./Depth-Anything-3", editable = true }
gsplat = "==1.5.3"
e3nn = "*"
plyfile = "*"
pillow-heif = "*"
xformers = "*"
open3d = "*"

# ============================================
# Feature: WildGS-SLAM
# ============================================
[feature.wildgs]
channels = ["nvidia"]
[feature.wildgs.dependencies]
python = "3.10.*"
gcc_linux-64 = "11.*"
gxx_linux-64 = "11.*"
# cuda-version = { version = "12.8.*", channel = "conda-forge" }
# cuda-nvcc = "12.8.*"
# cuda-runtime = "12.8.*"
# cuda-cudart = "12.8.*"
# cuda-libraries = "12.8.*"
# cuda-nvrtc = "12.8.*"

[feature.wildgs.pypi-dependencies]
numpy = "==1.26.3"
setuptools = "==78.1.1"
torchaudio = { version = "*", index = "https://download.pytorch.org/whl/cu128" }
xformers = "*"
pillow = "*"
imageio = "*"
joblib = "*"
pandas = "*"
scikit-image = "*"
scikit-learn = "*"
scipy = "*"
seaborn = "*"
PyOpenGL-accelerate = "*"
pyrender = "*"
ninja = "*"
timm = "==0.9.10"
plyfile = "==0.8.1"
tqdm = "*"
opencv-python = "==4.8.1.78"
munch = "*"
evo = "*"
open3d = "==0.17.0"
torchmetrics = "*"
imgviz = "*"
lpips = "*"
rich = "*"
kornia = "*"
PyQt5 = "*"
glfw = "*"
PyGLM = "*"
mmengine = "*"
mmcv-full = { url = "https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/mmcv_full-1.7.2-cp310-cp310-manylinux1_x86_64.whl" }
simple-knn = { path = "./WildGS-SLAM/thirdparty/simple-knn" }
lietorch = { path = "./WildGS-SLAM/thirdparty/lietorch" }
diff-gaussian-rasterization = { path = "./WildGS-SLAM/thirdparty/diff-gaussian-rasterization-w-pose" }
droid-backends = { path = "./WildGS-SLAM/", editable = true }
[feature.wildgs.pypi-options]
no-build-isolation = [
    "simple-knn",
    "lietorch",
    "diff-gaussian-rasterization",
    "droid-backends",
]


# ============================================
# ENVIRONMENTS
# ============================================
[environments]
ros2 = ["default", "cuda", "ros2"]
da3 = ["da3", "cuda"]
zed = ["default", "zed"]
wildgs = ["default", "cuda", "wildgs"]
